// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzjrt3fj11N3RWImAH8UHEuAhaRhjVzAo',
    appId: '1:1070599377855:web:cb3fdd585e86d49c71070a',
    messagingSenderId: '1070599377855',
    projectId: 'e-commerce-app-8998a',
    authDomain: 'e-commerce-app-8998a.firebaseapp.com',
    storageBucket: 'e-commerce-app-8998a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjbvXSmqlwxYr9-oRoFBLGK8mCBV98umg',
    appId: '1:1070599377855:android:2b7a7b242f6950e471070a',
    messagingSenderId: '1070599377855',
    projectId: 'e-commerce-app-8998a',
    storageBucket: 'e-commerce-app-8998a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Mwkx53kXs40DRHc_gmT1B-aUlpFIACM',
    appId: '1:1070599377855:ios:fe5139424a79f5fa71070a',
    messagingSenderId: '1070599377855',
    projectId: 'e-commerce-app-8998a',
    storageBucket: 'e-commerce-app-8998a.appspot.com',
    iosBundleId: 'com.example.productCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Mwkx53kXs40DRHc_gmT1B-aUlpFIACM',
    appId: '1:1070599377855:ios:aa685792b9d2f4a171070a',
    messagingSenderId: '1070599377855',
    projectId: 'e-commerce-app-8998a',
    storageBucket: 'e-commerce-app-8998a.appspot.com',
    iosBundleId: 'com.example.productCards.RunnerTests',
  );
}
